### PR TITLE
Updated stdev computation to account for issue dates

### PR DESCRIPTION
**Pull request by AlSaeed**

### CODE REVIEW

**Comment by AlSaeed** [comment]
@krivard This is the updated query for computing the stdev while only taking into account most recent issue per key.

**Comment by krivard** [comment]
Looks good, do all the tests pass?

**Comment by AlSaeed** [comment]
The unit tests pass, and `get_data_stdev_across_locations` doesn't have an integration test.

**Comment by krivard** [comment]
Hmmm, would you figure out some additional issue rows to add to [the direction integration test](https://github.com/AlSaeed/delphi-epidata/blob/c0d9948d466cfa963737a27ea8c2d4898f18840e/integrations/acquisition/covidcast/test_direction_updating.py#L50) that would fail if we were doing it wrong?

**Pull request closed without merging**
